// <auto-generated />
namespace PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class userarticle_Key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userarticle_Key));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091000275_user-article_Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
